### ISSUE TITLE
Feature distance to centroid 

### ISSUE THREAD

**Issue by eren-ck** [dbvis-ukon/movekit#10]
Compute the distance to the centroid of the swarm

**Comment by arjun-majumdar** [comment]
Completed

**Comment by eren-ck** [comment]
The computation to distance to centroid had some issues: 
The distance computation should be done for each time step and added up. The distance to the centroid for time step t is: 
> animal_k =  sqrt(centroid_t_x, centroid_t_y)   - (animal_k_t_x, animal_k_t_y)**2 

see [performance evaluation](https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy )

**Comment by arjun-majumdar** [comment]
Completed. I have attached the files-
centroid_calculation.py    [containing modified code]
distance_to_centroid-fish-5.csv   [containing 'distance_centroid' column for each time step 't' and for each animal_id 'aid']
