### ISSUE TITLE
Euclidean distance 

### ISSUE THREAD

**Issue by eren-ck** [dbvis-ukon/movekit#109]
Please see https://github.com/dbvis-ukon/movekit/blob/master/examples/02_extract_features.ipynb 
The compute the Euclidean distance feature results in inf values - please fix the bug

**Comment by Manuel030** [comment]
Can you provide an example? I've checked the mentioned notebook and at least for the data used there (fish.csv) the `euclidean_dist` function does not render any inf values. Under the hood, this function calls scipy's `pdist` function. So I suspect that the issue might be due to the input data
