### ISSUE TITLE
ts cluster

### ISSUE THREAD

**Issue by Manuel030** [dbvis-ukon/movekit#113]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-e6082ecfaa6b> in <module>
----> 1 clusters = mkit.ts_cluster(data, 2)
      2 clusters.head()

AttributeError: module 'movekit' has no attribute 'ts_cluster'

Upon investigation, I saw that `ts_cluster` is indeed implemented in clustering.py but as a comment. How should that be handled?

**Comment by Manuel030** [comment]
I've tested the function and in principle, it works. However, it does introduce an additional dependency, `tslearn`, and it performs poorly. Basically, it does KMeans on the extracted features.
Having in mind that we have st clustering now available in movekit, I suggest that we remove this function.

**Comment by eren-ck** [comment]
Than please remove the functionality 👍
