### ISSUE TITLE
Turning angle

### ISSUE THREAD

**Issue by eren-ck** [dbvis-ukon/movekit#120]
Feature extraction add a feature to compute the turning angle 
The method should return the difference between these headings and should be between -180 and 180 for each time step.

**Comment by Manuel030** [comment]
it works but I noticed one thing. The range is between -360 and +360. The headings/direction feature is defined on the domain -180 and +180 because of the `arctan2 ` function which is used. Suppose a mover has as direction -180 in t=0 and 180 in t=1, then turning will be 360 for t=1.

**Comment by eren-ck** [comment]
Is the range now between -360 and 360 or between -180 and 180? This is not clear from the above description.
Please also make sure that this special case is handled. For instance, boundary conditions between the different ranges

**Comment by Manuel030** [comment]
The range is between -360 and 360
