### ISSUE TITLE
Geo-Coordinates

### ISSUE THREAD

**Issue by eren-ck** [dbvis-ukon/movekit#122]
Support also instead of X and Y geographic coordinates

**Comment by Manuel030** [comment]
Some thoughts here:

There is no perfect solution: projection from sphere to plane is impossible to do right. 

But a practical solution exists: If input data is all from a similar area on earth's surface that can be approximated with an UTM zone for which projections to the plane exist (a UTM zone is 6° of longitude in width or 668km). 
An implementation for that exists in Python: https://github.com/Turbo87/utm

The easiest way to include this in `movekit` is to implement a function in `preprocess.py` that performs that transformation, potentially with a warning if input spans multiple zones.

**Comment by eren-ck** [comment]
Sounds good, please feel free to implement it and issue the warning if this heuristic generates errors.
In this context, it would of course also be practical if the movement data could be plotted on a map.
