### ISSUE TITLE
Pip installation

### ISSUE THREAD

**Issue by eren-ck** [dbvis-ukon/movekit#154]
Please resolve the following warning: 

`INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while`

**Comment by eren-ck** [comment]
Only a problem with Python 3.10.0

**Comment by TimKleinlein** [comment]
decided to go only with python 3.9 for now, -> done
