### ISSUE TITLE
module 'movekit' has no attribute 'getis_ord'

### ISSUE THREAD

**Issue by MZeinab** [dbvis-ukon/movekit#213]
I get this error!!
module 'movekit' has no attribute 'getis_ord'
Do you know how I can solve it?

**Comment by eren-ck** [comment]
Hello, 
I just updated the movekit package on PyPi. So just `pip install movekit -U` and afterward it should work. 

Cheers, 
Eren

**Comment by eren-ck** [comment]
Hey, 
please update the package, the error should be fixed. 

Cheers, 
Eren
