### ISSUE TITLE
Two install errors

### ISSUE THREAD

**Issue by JolleJolles** [dbvis-ukon/movekit#28]
When installing in new environment, the following error always arises:

`ERROR: tsfresh 0.12.0 has requirement pandas<=0.23.4,>=0.20.3, but you'll have pandas 0.24.2 which is incompatible.`

Also there are issues with the "__init__.py" file as it seems not able to load the relative files, like the csv module in the io folder:

```
>>> import movekit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Jolle/.virtualenvs/jolpy3/lib/python2.7/site-packages/movekit/__init__.py", line 1, in <module>
    from .io.csv import *
ImportError: No module named io.csv
```

**Comment by eren-ck** [comment]
Solved with #30 - modified the setup.py, the library now requires the correct packages and also python>=3.5
