### ISSUE TITLE
Error distance and direction

### ISSUE THREAD

**Issue by eren-ck** [dbvis-ukon/movekit#53]
* divide by zero encountered in double_scalars direction = math.degrees(math.atan((y2 - y1) / (x2 - x1)))
* RuntimeWarning: invalid value encountered in double_scalar direction = math.degrees(math.atan((y2 - y1) / (x2 - x1)))

Use scipy distance functions

**Comment by arjun-majumdar** [comment]
I have fixed the problem by changing the code for calculation of direction by checking that the denominator i.e., (x2 - x1) is NOT zero. Because while parsing the dataset, there are many indexes where x1 is equal to x2 thereby making divide by zero happening!
